AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Scrape FFXIV player data

Parameters:
  DynamoDBTableName:
    Type: String
    Default: FFXIV
    Description: Name the DynamoDB table
  DataBucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package and base CSV
  DataS3Key:
    Type: String
    Description: CSV file which contains base template for DynamoDB
  NotificationEmail:
    Type: String
    Description: An e-mail address which to send a notification once the task is done

Resources:
  Database:
    Type: AWS::DynamoDB::Table
    Properties:
      Tags:
        - Key: Project
          Value: FFXIV
      TableClass: STANDARD
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ImportSourceSpecification:
        InputCompressionType: NONE
        InputFormat: CSV
        S3BucketSource:
          S3Bucket: !Ref DataBucket
          S3KeyPrefix: !Ref DataS3Key
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  ScraperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer
      Description: Lambda Layer for web scraping
      CompatibleRuntimes:
        - python3.14
      RetentionPolicy: Delete
  ScraperLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  ScraperLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FinalFantasyScraperFucntion
      ReservedConcurrentExecutions: 1
      CodeUri: ./scraper
      Handler: lambda.lambda_handler
      Runtime: python3.14
      Role: !GetAtt ScraperLambdaExecutionRole.Arn
      Timeout: 360
      MemorySize: 384
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTableName
      Layers:
        - !Ref ScraperLayer
  ScraperEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ScraperEventRule
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ScraperLambdaFunction.Arn
          Id: ScraperTarget
  ScraperLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScraperLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScraperEventRule.Arn
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ScraperNotificationTopic
      TopicName: ScraperNotificationTopic
  NotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref NotificationEmail
      Protocol: email-json
      TopicArn: !Ref NotificationTopic
  DynamoDBThroughputAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref NotificationTopic
      AlarmDescription: "Scraper DynamoDB thoughput has been 0 for an hour. Either it's finished or something went wrong"
      AlarmName: "DynamoDBThroughputAlarm-Zero"
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTableName
      Period: 600 # seconds
      EvaluationPeriods: 6
      MetricName: ConsumedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching
